# Generated by Django 4.0.4 on 2022-05-27 05:51

from django.db import migrations, models
from django.core.management import call_command

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
