# Generated by Django 4.0.4 on 2022-05-27 06:04

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command

class Migration(migrations.Migration):

    def load_from_fixtures(apps, schema_editor):
        call_command("loaddata", "loginData", verbosity=2)

    dependencies = [
        ('login', '0002_perfiles_usuario_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.perfiles'),
        ),
        migrations.RunPython(load_from_fixtures)
    ]


