# Generated by Django 4.0.2 on 2022-05-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfiles',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
