# Generated by Django 4.0.4 on 2022-06-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_perfiles_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='huella',
            field=models.TextField(blank=True),
        ),
    ]
