# Generated by Django 4.0.4 on 2022-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_usuario_huella'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
