# Generated by Django 4.0.4 on 2023-03-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_usuario_apellidos_usuario_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='huella',
            field=models.TextField(blank=True, null=True),
        ),
    ]
