# Generated by Django 4.0.4 on 2023-03-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_usuario_huella'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisosusuarios',
            name='pmiasistencia',
            field=models.IntegerField(default=0),
        ),
    ]
