# Generated by Django 4.0.4 on 2023-03-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_permisosusuarios_pmiasistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lunes', models.IntegerField(default=0)),
                ('entradalunes', models.TimeField(blank=True, null=True)),
                ('salidalunes', models.TimeField(blank=True, null=True)),
                ('martes', models.IntegerField(default=0)),
                ('entradamartes', models.TimeField(blank=True, null=True)),
                ('salidamartes', models.TimeField(blank=True, null=True)),
                ('miercoles', models.IntegerField(default=0)),
                ('entradamiercoles', models.TimeField(blank=True, null=True)),
                ('salidamiercoles', models.TimeField(blank=True, null=True)),
                ('jueves', models.IntegerField(default=0)),
                ('entradajueves', models.TimeField(blank=True, null=True)),
                ('salidajueves', models.TimeField(blank=True, null=True)),
                ('viernes', models.IntegerField(default=0)),
                ('entradaviernes', models.TimeField(blank=True, null=True)),
                ('salidaviernes', models.TimeField(blank=True, null=True)),
                ('sabado', models.IntegerField(default=0)),
                ('entradasabado', models.TimeField(blank=True, null=True)),
                ('salidasabado', models.TimeField(blank=True, null=True)),
                ('domingo', models.IntegerField(default=0)),
                ('entradadomingo', models.TimeField(blank=True, null=True)),
                ('salidadomingo', models.TimeField(blank=True, null=True)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
