# Generated by Django 4.0.4 on 2023-03-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_horariolaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariolaboral',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
