version: '3.7'

services:
  base_de_datos:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
    environment:
      - POSTGRES_USER=laan
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=intranet
    ports:
      - '3013:5432'

  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "2904:8000"
    


volumes:
  postgres_data:
