# Generated by Django 4.0.4 on 2022-12-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intranet', '0072_configuracionadministrativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAsignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoConservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupocampo_activo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrigenFondo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procendencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_activo', models.BooleanField(default=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.familia')),
            ],
        ),
        migrations.CreateModel(
            name='campo_activo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('numero_serie', models.CharField(max_length=100)),
                ('codigo_barra', models.CharField(max_length=100)),
                ('valor_total', models.IntegerField(blank=True, default=0, null=True)),
                ('numero_factura', models.IntegerField(blank=True, default=0, null=True)),
                ('descripcion_baja', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('area_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_asignacion', to='inventario.areaasignacion')),
                ('categorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorizacion', to='inventario.categorizacion')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centro_costo', to='inventario.centrocosto')),
                ('estado_conservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_conservacion', to='inventario.estadoconservacion')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='inventario.grupocampo_activo')),
                ('inventariable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventariable', to='inventario.inventariable')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_educativo', to='inventario.niveleducativo')),
                ('origen_fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_fondo', to='inventario.origenfondo')),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedencia', to='inventario.procendencia')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='intranet.salas')),
            ],
        ),
    ]
