# Generated by Django 4.0.4 on 2022-12-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo_activo',
            name='fecha_compra',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='campo_activo',
            name='rut_proveedor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
