# Generated by Django 4.0.4 on 2022-12-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_campo_activo_fecha_compra_campo_activo_rut_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='metabase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='campo_activo',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campo_activo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
