# Generated by Django 4.0.2 on 2022-05-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horainicio', models.CharField(max_length=100)),
                ('horafinal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profesores',
            name='rut',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SalasPedidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('idProfesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.profesores')),
                ('idSala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.salas')),
                ('idhorario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.horarios')),
            ],
        ),
    ]
