# Generated by Django 4.0.4 on 2022-05-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_horarios_salas_profesores_rut_salaspedidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cordinador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Impresor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profesores',
            name='apellido',
            field=models.CharField(default='apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='profesores',
            name='correo',
            field=models.EmailField(default='Correo', max_length=254),
        ),
        migrations.AddField(
            model_name='profesores',
            name='password',
            field=models.CharField(default='Correo', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='rut',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PeticionesImpresion',
            fields=[
                ('numeroConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='')),
                ('fechaPeticion', models.DateTimeField()),
                ('fechaEstimadaImpresion', models.DateTimeField()),
                ('cantidadImpresion', models.IntegerField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.asignaturas')),
                ('cordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cordinador')),
                ('cursoDestinado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cursos')),
                ('datosProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.profesores')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.estados')),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturasAsignadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idasignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.asignaturas')),
                ('idprofe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.profesores')),
            ],
        ),
    ]
