# Generated by Django 4.0.4 on 2022-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_asignaturas_cordinador_cursos_estados_impresor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='archivo',
            field=models.FileField(upload_to='Impresiones'),
        ),
    ]
