# Generated by Django 4.0.2 on 2022-05-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_alter_peticionesimpresion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='cordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.cordinador'),
        ),
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='fechaEstimadaImpresion',
            field=models.DateTimeField(default='2222-11-12'),
        ),
    ]
