# Generated by Django 4.0.2 on 2022-05-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_alter_peticionesimpresion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='archivo',
            field=models.TextField(),
        ),
    ]
