# Generated by Django 4.0.2 on 2022-05-25 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_alter_peticionesimpresion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.estados'),
        ),
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='fechaEstimadaImpresion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='fechaPeticion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
