# Generated by Django 4.0.2 on 2022-05-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_delete_impresor_alter_asignaturasasignadas_idprofe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='fechaEstimadaImpresion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='fechaPeticion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
