# Generated by Django 4.0.2 on 2022-06-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_alter_peticionesimpresion_fechaestimadaimpresion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaspedidas',
            name='fechaPeticion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
