# Generated by Django 4.0.2 on 2022-06-02 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_salaspedidas_fechapeticion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosSalasPedidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.TextField()),
                ('idSalaPedida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.salaspedidas')),
            ],
        ),
    ]
