# Generated by Django 4.0.4 on 2022-06-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_rename_descripcion_salaspedidas_objetivoaprendizaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaspedidas',
            name='idAsignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.asignaturas'),
        ),
        migrations.AddField(
            model_name='salaspedidas',
            name='idCurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.cursos'),
        ),
    ]
