# Generated by Django 4.0.4 on 2022-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0014_salaspedidas_idasignatura_salaspedidas_idcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaspedidas',
            name='fechaPeticion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
