# Generated by Django 4.0.4 on 2022-07-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_matriculaalumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculaalumno',
            old_name='revisaryresponderinformacionmediantemediosdecomunicacionestablecida',
            new_name='revisarinformacionmediantemediosdecomunicacionestablecida',
        ),
    ]
