# Generated by Django 4.0.4 on 2022-07-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0018_rename_revisaryresponderinformacionmediantemediosdecomunicacionestablecida_matriculaalumno_revisarin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculaalumno',
            old_name='revisarinformacionmediantemediosdecomunicacionestablecida',
            new_name='revisaryresponderinformacionmediantemediosdecomunicacion',
        ),
    ]
