# Generated by Django 4.0.4 on 2022-08-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_peticionesimpresion_doblecara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturas',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='cantidadestudiantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salas',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='estado',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
    ]
