# Generated by Django 4.0.4 on 2022-08-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0021_asignaturas_orden_cursos_cantidadestudiantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticionesimpresion',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.CreateModel(
            name='DestinatariosCursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cursos')),
            ],
        ),
    ]
