# Generated by Django 4.0.4 on 2022-08-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0023_alter_peticionesimpresion_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticionesimpresion',
            name='fechaImpresionEntregada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
