# Generated by Django 4.0.4 on 2022-08-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_usuario_imagen'),
        ('intranet', '0025_noticiasfront'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaHablado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpinionesProfesores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
                ('tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.temahablado')),
            ],
        ),
    ]
