# Generated by Django 4.0.4 on 2022-08-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0026_temahablado_opinionesprofesores'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuellaAlumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=400)),
                ('nombre', models.CharField(max_length=400)),
                ('junaeb', models.BooleanField(default=False)),
                ('huella', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsitenciaAlumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaasitencias', models.DateTimeField(blank=True, null=True)),
                ('horasalida', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.huellaalumno')),
            ],
        ),
    ]
