# Generated by Django 4.0.4 on 2022-08-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0027_huellaalumno_asitenciaalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='huellaalumno',
            name='correo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='huellaalumno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.cursos'),
        ),
    ]
