# Generated by Django 4.0.4 on 2022-08-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0028_huellaalumno_correo_huellaalumno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='asitenciaalumno',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProblemaAsistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaproblema', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.huellaalumno')),
            ],
        ),
    ]
