# Generated by Django 4.0.4 on 2022-08-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0029_asitenciaalumno_activo_problemaasistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asitenciaalumno',
            old_name='activo',
            new_name='atrasoresuelto',
        ),
    ]
