# Generated by Django 4.0.4 on 2022-08-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0030_rename_activo_asitenciaalumno_atrasoresuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='huellaalumno',
            name='correoapoderado',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='huellaalumno',
            name='telefonoapoderado',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
