# Generated by Django 4.0.4 on 2022-09-14 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0032_categoriamantencion_mantencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursosMantencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
                ('costoaprox', models.IntegerField()),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.mantencion')),
            ],
        ),
    ]
