# Generated by Django 4.0.4 on 2022-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0034_categoriaproductocra_productocra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproductocra',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
