# Generated by Django 4.0.4 on 2022-09-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0035_alter_categoriaproductocra_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocra',
            name='Activo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocra',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocra',
            name='codigobarra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocra',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocra',
            name='infinito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocra',
            name='limitecantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocra',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocra',
            name='posicion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocra',
            name='vecespedido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
