# Generated by Django 4.0.4 on 2022-09-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0036_alter_productocra_activo_alter_productocra_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocra',
            old_name='img',
            new_name='imagen',
        ),
    ]
