# Generated by Django 4.0.4 on 2022-10-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_usuario_imagen'),
        ('intranet', '0037_rename_img_productocra_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLibrosCra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeticionesLibrosCra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('ncopia', models.IntegerField()),
                ('fechapeticion', models.DateTimeField(blank=True, null=True)),
                ('fechadevolucion', models.DateTimeField(blank=True, null=True)),
                ('idcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.categoriaproductocra')),
                ('idproducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.productocra')),
                ('idprofesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LibrosCra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('limitecantidad', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('infinito', models.IntegerField(blank=True, null=True)),
                ('Activo', models.IntegerField(blank=True, null=True)),
                ('autor', models.TextField(blank=True, null=True)),
                ('posicion', models.TextField(blank=True, null=True)),
                ('codigobarra', models.TextField(blank=True, null=True)),
                ('vecespedido', models.IntegerField(blank=True, null=True)),
                ('idcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.categoriaproductocra')),
            ],
        ),
    ]
