# Generated by Django 4.0.4 on 2022-10-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0039_remove_peticioneslibroscra_idprofesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroscra',
            name='idcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.categorialibroscra'),
        ),
        migrations.AlterField(
            model_name='peticioneslibroscra',
            name='idcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.categorialibroscra'),
        ),
    ]
