# Generated by Django 4.0.4 on 2022-10-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0040_alter_libroscra_idcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticioneslibroscra',
            name='idproducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.libroscra'),
        ),
        migrations.AlterField(
            model_name='peticioneslibroscra',
            name='ncopia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
