# Generated by Django 4.0.4 on 2022-10-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0044_alter_peticionesproductocra_idprofesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaalumno',
            name='datoshuella',
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='becaindigena',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='otrabeca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='perteneceprogramasocial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='preferente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='prioritario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='registrosocialdehogares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='tienejunaeb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='alergico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='consultorioocesfam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='encasodeemergenciacomunicarsecon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='enfermedadcronica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='hijoconimpedimentofisico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='optaporuncredo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='sistemadesalud',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='tomamedicamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
