# Generated by Django 4.0.4 on 2022-10-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0045_remove_matriculaalumno_datoshuella_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaalumno',
            name='estudiantenuevo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='optaporreligion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='perteneceaproyectodeintegracionescolar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='perteneceprogramasocial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='preferente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='prioritario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='registrosocialdehogares',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='tienejunaeb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
