# Generated by Django 4.0.4 on 2022-10-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0047_matriculaseccionpersonalizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculasalternativasopcion',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculasalternativasopcion',
            name='valor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculasopcionpersonalizada',
            name='tipodeopcion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
