# Generated by Django 4.0.4 on 2022-10-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0048_alter_matriculasalternativasopcion_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaalumno',
            name='firmaapoderados',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='imagenalumno',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
