# Generated by Django 4.0.4 on 2022-10-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0049_matriculaalumno_firmaapoderados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculasdatosopcion',
            name='idopcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.matriculasopcionpersonalizada'),
        ),
        migrations.AddField(
            model_name='matriculasdatosopcion',
            name='valor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='firmaapoderados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
