# Generated by Django 4.0.4 on 2022-10-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0051_cursos_tipodecurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosAdjuntosMatricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('idmatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.matriculaalumno')),
            ],
        ),
    ]
