# Generated by Django 4.0.4 on 2022-10-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0052_documentosadjuntosmatricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='enfermedades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuariosyomi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.CharField(blank=True, max_length=300, null=True)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
