# Generated by Django 4.0.4 on 2022-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0053_enfermedades_medicamentos_usuariosyomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='libroscra',
            name='editorial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
