# Generated by Django 4.0.4 on 2022-11-08 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0055_alter_peticioneslibroscra_idhuella_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasAlumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n1', models.CharField(max_length=50)),
                ('n2', models.CharField(max_length=50)),
                ('n3', models.CharField(max_length=50)),
                ('n4', models.CharField(max_length=50)),
                ('n5', models.CharField(max_length=50)),
                ('n6', models.CharField(max_length=50)),
                ('n7', models.CharField(max_length=50)),
                ('n8', models.CharField(max_length=50)),
                ('n9', models.CharField(max_length=50)),
                ('n10', models.CharField(max_length=50)),
                ('n11', models.CharField(max_length=50)),
                ('n12', models.CharField(max_length=50)),
                ('n13', models.CharField(max_length=50)),
                ('n14', models.CharField(max_length=50)),
                ('n15', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.huellaalumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.asignaturas')),
            ],
        ),
    ]
