# Generated by Django 4.0.4 on 2022-11-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0056_notasalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasalumno',
            name='indicador',
            field=models.CharField(default='B', max_length=50),
        ),
    ]
