# Generated by Django 4.0.4 on 2022-11-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0059_noticiasfront_interno'),
    ]

    operations = [
        migrations.CreateModel(
            name='sintomas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('gravedad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enfermedades',
            name='gravedad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='sintomasdeenfermedades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.enfermedades')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.sintomas')),
            ],
        ),
        migrations.CreateModel(
            name='medicamentoenfermedades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.enfermedades')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.medicamentos')),
            ],
        ),
    ]
