# Generated by Django 4.0.4 on 2022-11-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0061_calendario_alter_noticiasfront_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaspedidas',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaspedidas',
            name='observacionpendiente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
