# Generated by Django 4.0.4 on 2022-11-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_usuario_huella'),
        ('intranet', '0063_remove_calendario_d1_remove_calendario_d10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='abril',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='agosto',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='diciembre',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='enero',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='febrero',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='julio',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='junio',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='marzo',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='mayo',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='noviembre',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='octubre',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='septiembre',
        ),
        migrations.AddField(
            model_name='calendario',
            name='dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='nombredia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='tipodia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ObjetivoAprendizaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroaprendizaje', models.IntegerField(blank=True, null=True)),
                ('tituloaprendizaje', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.asignaturas')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.cursos')),
                ('diafinal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diafinal', to='intranet.calendario')),
                ('diainicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.calendario')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
