# Generated by Django 4.0.4 on 2022-11-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0065_remove_objetivoaprendizaje_diafinal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='diafinal',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='diainicio',
        ),
        migrations.CreateModel(
            name='EventoDias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idcalendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.calendario')),
                ('idevento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.eventos')),
            ],
        ),
    ]
