# Generated by Django 4.0.4 on 2022-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0066_remove_eventos_diafinal_remove_eventos_diainicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='publica',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
