# Generated by Django 4.0.4 on 2022-11-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_usuario_huella'),
        ('intranet', '0067_salas_publica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivoaprendizaje',
            old_name='descripcion',
            new_name='enfasis',
        ),
        migrations.RenameField(
            model_name='objetivoaprendizaje',
            old_name='estado',
            new_name='horassemanales',
        ),
        migrations.RenameField(
            model_name='objetivoaprendizaje',
            old_name='tituloaprendizaje',
            new_name='indicadoresdelogro',
        ),
        migrations.RenameField(
            model_name='objetivoaprendizaje',
            old_name='numeroaprendizaje',
            new_name='semestre',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='nsemana',
        ),
        migrations.AddField(
            model_name='objetivoaprendizaje',
            name='mes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivoaprendizaje',
            name='objetivodeaprendizaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivoaprendizaje',
            name='semanas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objetivoaprendizaje',
            name='tema',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objetivoaprendizaje',
            name='trimestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivoaprendizaje',
            name='unidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConstanciasSalas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('estado', models.IntegerField(blank=True)),
                ('npeticion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.salaspedidas')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadesAprendizaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreactividad', models.TextField(blank=True, null=True)),
                ('evidenciaaprendizaje', models.TextField(blank=True, null=True)),
                ('criteriodeevaluacion', models.TextField(blank=True, null=True)),
                ('tipodeevaluacion', models.TextField(blank=True, null=True)),
                ('idobjetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.objetivoaprendizaje')),
            ],
        ),
    ]
