# Generated by Django 4.0.4 on 2022-11-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0068_rename_descripcion_objetivoaprendizaje_enfasis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivoaprendizaje',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
