# Generated by Django 4.0.4 on 2022-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0069_objetivoaprendizaje_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivoaprendizaje',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
