# Generated by Django 4.0.4 on 2022-11-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0070_alter_objetivoaprendizaje_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiendasmedicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='precio',
        ),
        migrations.CreateModel(
            name='medicamentoentienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('idmedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.medicamentos')),
                ('idtienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.tiendasmedicamentos')),
            ],
        ),
    ]
