# Generated by Django 4.0.4 on 2022-12-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0071_tiendasmedicamentos_remove_medicamentos_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAdministrativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('divisiondeyear', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='notasalumno',
            old_name='indicador',
            new_name='indicador1',
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='diasasistidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='diasnoasistidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='indicador2',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='indicador3',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='indicador4',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n16',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n17',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n18',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n19',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n21',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n22',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n23',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n24',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n25',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n26',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n27',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n28',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n29',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='n30',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.matriculaalumno'),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n13',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n14',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n15',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notasalumno',
            name='n9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TonerImpresion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreimpresora', models.CharField(max_length=200)),
                ('tintaactual', models.IntegerField(blank=True, null=True)),
                ('hojasactual', models.IntegerField(blank=True, null=True)),
                ('salaalojada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.salas')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialToner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('cantidadtinta', models.IntegerField(blank=True, null=True)),
                ('hojasactual', models.IntegerField(blank=True, null=True)),
                ('impresora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.tonerimpresion')),
            ],
        ),
    ]
