# Generated by Django 4.0.4 on 2022-12-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0073_matriculaalumno_yearmatricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaalumno',
            name='nmatricula',
        ),
        migrations.AlterField(
            model_name='matriculaalumno',
            name='cursodematricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.cursos'),
        ),
    ]
