# Generated by Django 4.0.4 on 2022-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0074_remove_matriculaalumno_nmatricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaalumno',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
