# Generated by Django 4.0.4 on 2022-12-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0083_notasalumno_promedio1_notasalumno_promedio2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalumno',
            name='promedioanual',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
