# Generated by Django 4.0.4 on 2022-12-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0084_alter_notasalumno_promedioanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaalumno',
            name='diasasistidos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
