# Generated by Django 4.0.4 on 2022-12-30 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0085_alter_matriculaalumno_diasasistidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='finals1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finals1', to='intranet.calendario'),
        ),
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='finals2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finals2', to='intranet.calendario'),
        ),
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='finals3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finals3', to='intranet.calendario'),
        ),
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='finals4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finals4', to='intranet.calendario'),
        ),
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='iniciodeasistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iniciodeasistencia', to='intranet.calendario'),
        ),
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
