# Generated by Django 4.0.4 on 2023-01-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0086_configuracionadministrativa_finals1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculaalumno',
            old_name='diasasistidos',
            new_name='diasasistidos1',
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='diasasistidos2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='diasasistidos3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='diasasistidos4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
