# Generated by Django 4.0.4 on 2023-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0087_rename_diasasistidos_matriculaalumno_diasasistidos1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='cantidad1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='cantidad2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='cantidad3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='cantidad4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
