# Generated by Django 4.0.4 on 2023-01-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_usuario_huella'),
        ('intranet', '0088_configuracionadministrativa_cantidad1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.usuario'),
        ),
    ]
