# Generated by Django 4.0.4 on 2023-02-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0089_salas_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivoaprendizaje',
            old_name='enfasis',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='objetivoaprendizaje',
            old_name='horassemanales',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='indicadoresdelogro',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='objetivodeaprendizaje',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='semanas',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='trimestre',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='year',
        ),
        migrations.AddField(
            model_name='objetivoaprendizaje',
            name='titulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='salaspedidas',
            name='oa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.objetivoaprendizaje'),
        ),
        migrations.AlterField(
            model_name='objetivoaprendizaje',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.asignaturas'),
        ),
        migrations.AlterField(
            model_name='objetivoaprendizaje',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.cursos'),
        ),
        migrations.DeleteModel(
            name='ActividadesAprendizaje',
        ),
    ]
