# Generated by Django 4.0.4 on 2023-02-13 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0090_rename_enfasis_objetivoaprendizaje_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaalumno',
            name='niveljunaeb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='HistorialJunaeb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ncomida', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.matriculaalumno')),
            ],
        ),
    ]
