# Generated by Django 4.0.4 on 2023-02-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0092_permisosusuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPublico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fechaemision', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PermisosUsuarios',
        ),
        migrations.AddField(
            model_name='matriculaalumno',
            name='entramite',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registropublico',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.matriculaalumno'),
        ),
    ]
