# Generated by Django 4.0.4 on 2023-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0095_registropublico_fechaaceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropublico',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
