# Generated by Django 4.0.4 on 2023-03-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0098_libroscra_cursodestinado_libroscra_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionadministrativa',
            name='horadeatraso',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
