# Generated by Django 4.0.4 on 2023-03-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_usuario_huella'),
        ('intranet', '0099_configuracionadministrativa_horadeatraso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('horaentrada', models.DateTimeField()),
                ('horasalida', models.DateTimeField()),
                ('iddocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
