# Generated by Django 4.0.4 on 2023-05-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0101_alter_asistenciadocente_horasalida'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CajaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_oferta', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CajaVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_compra', models.IntegerField(default=0)),
                ('hora_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CajaIngredientesProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_ingrediente', models.IntegerField(default=0)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cajaingrediente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cajaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='CajaDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('sub_total', models.IntegerField(default=0)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cajaproducto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cajaventa')),
            ],
        ),
    ]
