# Generated by Django 4.0.4 on 2023-05-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0102_cajaingrediente_cajaproducto_cajaventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
